--- #YAML:1.0
name:               Date-Range
version:            1.41
abstract:           work with a range of dates
author:
    - Tony Bowden <kasei@tmtm.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Simple:  0.03
    Test::More:    0.04
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
